// Standalone HOST tool (NOT part of the app_server build). Regenerates
// SystemPaletteMap.h whenever kSystemPalette changes. The math is byte-based
// and therefore endian-independent, so it runs correctly on any host:
//   g++ -O2 -I headers/private/interface generate_palette_map.cpp -o genmap
//   ./genmap > SystemPaletteMap.h
//
// The generated tables are the precomputed color_map index/inversion maps that
// FillColorMap() (SystemPalette.cpp) used to build at runtime -- an 8.4M
// iteration nearest-color search (32768 * 256) that cost ~22s at every
// app_server startup on slow/emulated PowerPC.

#include <stdio.h>
#include <limits.h>
#include <stdint.h>
typedef uint8_t uint8; typedef uint32_t uint32; typedef int32_t int32;
struct rgb_color { uint8 red, green, blue, alpha; };
#include <Palette.h>   // the real kSystemPalette (single source of truth)

static inline uint32
color_distance(uint8 red1, uint8 green1, uint8 blue1,
               uint8 red2, uint8 green2, uint8 blue2)
{
    int rd = (int)red1 - (int)red2;
    int gd = (int)green1 - (int)green2;
    int bd = (int)blue1 - (int)blue2;
    int rmean = ((int)red1 + (int)red2) / 2;
    return (((512 + rmean) * rd * rd) >> 8)
            + 4 * gd * gd
            + (((767 - rmean) * bd * bd) >> 8);
}
static inline uint8
FindClosestColor(const rgb_color &color, const rgb_color *palette)
{
    uint8 closestIndex = 0; unsigned closestDistance = UINT_MAX;
    for (int32 i = 0; i < 256; i++) {
        const rgb_color &c = palette[i];
        unsigned distance = color_distance(color.red, color.green, color.blue,
                                           c.red, c.green, c.blue);
        if (distance < closestDistance) { closestIndex = (uint8)i; closestDistance = distance; }
    }
    return closestIndex;
}
static inline rgb_color
InvertColor(const rgb_color &color)
{
    if (color.red == 255 && color.green == 255 && color.blue == 255) return color;
    rgb_color inverted; inverted.red = 255 - color.red; inverted.green = 255 - color.green;
    inverted.blue = 255 - color.blue; inverted.alpha = 255; return inverted;
}
int main() {
    printf("// Auto-generated by generate_palette_map.cpp from kSystemPalette. Do not edit.\n");
    printf("// Precomputed color_map index/inversion tables (see SystemPalette.cpp).\n");
    printf("#ifndef SYSTEM_PALETTE_MAP_H\n#define SYSTEM_PALETTE_MAP_H\n\n");
    printf("static const uint8 kSystemColorMapIndex[32768] = {\n");
    for (int32 color = 0; color < 32768; color++) {
        rgb_color c; c.red=(color&0x7c00)>>7; c.green=(color&0x3e0)>>2; c.blue=(color&0x1f)<<3; c.alpha=255;
        printf("%d,", FindClosestColor(c, kSystemPalette));
        if ((color & 31) == 31) printf("\n");
    }
    printf("};\n\nstatic const uint8 kSystemColorMapInversion[256] = {\n");
    for (int32 index = 0; index < 256; index++) {
        rgb_color inv = InvertColor(kSystemPalette[index]);
        printf("%d,", FindClosestColor(inv, kSystemPalette));
        if ((index & 31) == 31) printf("\n");
    }
    printf("};\n\n#endif\n");
    return 0;
}
