name: Wii Bootloader CI

on:
  push:
    branches: [ "master", "main", "powerpc" ]
  pull_request:
    branches: [ "master", "main", "powerpc" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitppc:latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install Haiku Dependencies
      run: |
        apt-get update
        apt-get install -y git nasm flex bison gawk \
                                mtools xorriso zlib1g-dev \
                                mkisofs python3 wget libzstd-dev \
                                u-boot-tools xattr build-essential

    - name: Download Buildtools
      run: |
        cd ..
        git clone https://review.haiku-os.org/buildtools.git
        cd buildtools/jam
        make
        ./jam0 install

    - name: Configure Haiku for PowerPC
      run: |
        mkdir -p /work
        mkdir -p generated.ppc
        cd generated.ppc
        ../configure --cross-tools-source ../../buildtools --build-cross-tools ppc

    - name: Build Wii Bootloader
      run: |
        cd generated.ppc
        jam -q '<wii>boot_platform_wii.o'

    - name: Build Wii SDHC Driver
      run: |
        cd generated.ppc
        jam -q wii_sdhc

    - name: Build 4GB Haiku Root Image
      run: |
        cd generated.ppc
        jam -q -sHAIKU_IMAGE_SIZE=4096 @image

